cmake_minimum_required(VERSION 3.28)

SET (CMAKE_C_COMPILER             "/usr/bin/clang")
SET (CMAKE_C_STANDARD             17)
SET (CMAKE_C_STANDARD_REQUIRED    ON)
SET (CMAKE_C_FLAGS                "-Wall -std=c17")
SET (CMAKE_C_FLAGS_DEBUG          "-g")
SET (CMAKE_C_FLAGS_MINSIZEREL     "-Os -DNDEBUG")
SET (CMAKE_C_FLAGS_RELEASE        "-O4 -DNDEBUG")
SET (CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g")

SET (CMAKE_CXX_COMPILER          "/usr/bin/clang++")
SET (CMAKE_CXX_STANDARD          20)
SET (CMAKE_CXX_STANDARD_REQUIRED ON)
SET (CMAKE_CXX_FLAGS             "${CMAKE_CXX_FLAGS} -std=c++20")
SET (CMAKE_CXX_FLAGS_DEBUG          "-g")
SET (CMAKE_CXX_FLAGS_MINSIZEREL     "-Os -DNDEBUG")
SET (CMAKE_CXX_FLAGS_RELEASE        "-O4 -DNDEBUG")
SET (CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g")

SET (CMAKE_AR      "/usr/bin/llvm-ar")
SET (CMAKE_LINKER  "/usr/bin/llvm-link")
SET (CMAKE_RANLIB  "/usr/bin/llvm-ranlib")
SET (CMAKE_NM      "/usr/bin/llvm-nm")
SET (CMAKE_STRIP   "/usr/bin/llvm-strip")
SET (CMAKE_SIZE    "/usr/bin/llvm-size")
SET (CMAKE_OBJDUMP "/usr/bin/llvm-objdump")
SET (CMAKE_OBJCOPY "/usr/bin/llvm-objcopy")
